---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-KAFA21-DV1673-H23-LP2
domain_name: devopsbth.tech

admin_email: kafa21@student.bth.se

vmtags:
  StudentId: kafa21

pub_ssh_key_location: "/home/falkendev/.ssh/azure.pub"

lb_method: least_conn

server_user: "deploy"
server_user_pass: "devopsbth"
server_user_groups:
  - sudo
