name: Rolling Update Deployment

on:
  release:
    types: [created]

jobs:
  docker-publish:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit

  deploy:
    needs: docker-publish
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.azure_ssh }}

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Rolling Update Playbook
        run: ansible-playbook -i ansible/hosts ansible/deploy.yml -e "github_release_tag=${{ github.event.release.tag_name }}"
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
